

namespace FreyrCommon.Models
{
    //do not modify this class its a copy from SenseCalAgentDatapodoubleSetTemplate in the 
    //autogenerated file DatapodoubleTemplates.cs
    public class QLikSenseCalInfo
    {
        /// <summary>
        /// The datapodouble "SenseCalAgent.TotalTokens"
        /// </summary>
        public  double TotalTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.AvailableTokens"
        /// </summary>
        public  double AvailableTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.User.AllocatedTokens"
        /// </summary>
        public  double UserAllocatedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.User.UsedTokens"
        /// </summary>
        public  double UserUsedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.User.QuarantinedTokens"
        /// </summary>
        public  double UserQuarantinedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Login.AllocatedTokens"
        /// </summary>
        public  double LoginAllocatedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Login.UsedTokens"
        /// </summary>
        public  double LoginUsedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Login.UnavailableTokens"
        /// </summary>
        public  double LoginUnavailableTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Application.AllocatedTokens"
        /// </summary>
        public  double ApplicationAllocatedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Application.UsedTokens"
        /// </summary>
        public  double ApplicationUsedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Application.QuarantinedTokens"
        /// </summary>
        public  double ApplicationQuarantinedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Professional.AllocatedTokens"
        /// </summary>
        public  double ProfessionalAllocatedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Professional.UsedTokens"
        /// </summary>
        public  double ProfessionalUsedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Professional.QuarantinedTokens"
        /// </summary>
        public  double ProfessionalQuarantinedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Analyzer.AllocatedTokens"
        /// </summary>
        public  double AnalyzerAllocatedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Analyzer.UsedTokens"
        /// </summary>
        public  double AnalyzerUsedTokens { get; set;}

        /// <summary>
        /// The datapodouble "SenseCalAgent.Analyzer.QuarantinedTokens"
        /// </summary>
        public  double AnalyzerQuarantinedTokens { get; set;}
    }
}
