namespace FreyrCommon.Models
{
    //do not modify this class its a copy from SenseCalAgentDatapodoubleSetTemplate in the 
    //autogenerated file DatapodoubleTemplates.cs
    public class QlikSenseLicenseInfo
    {
        /// <summary>
        /// The datapoint "SenseLicenseAgent.ExpireDate"
        /// </summary>
        public string ExpireDate { get; set;}

        /// <summary>
        /// The datapoint "SenseLicenseAgent.LicenseSerialNo"
        /// </summary>
        public string LicenseSerialNo { get; set;}

        /// <summary>
        /// The datapoint "SenseLicenseAgent.IsExpired"
        /// </summary>
        public double IsExpired { get; set;}

        /// <summary>
        /// The datapoint "SenseLicenseAgent.ExpiredReason"
        /// </summary>
        public string ExpiredReason { get; set;}

        /// <summary>
        /// The datapoint "SenseLicenseAgent.IsBlacklisted"
        /// </summary>
        public double IsBlacklisted { get; set;}
    }
}
